#Question 1
setwd("/Users/yunluli/Desktop/stat5170/hw3")
berk<-scan("berkeley.dat", what=list(double(0),double(0),double(0)))
time<-berk[[1]]
berkeley<-berk[[2]]
#(a)
plot(berkeley~time, ylab="yearly temperature",main="Berkeley Temperature")
#(b)
lr<-lm(berkeley~time)
summary(lr)
abline(lr,col='red')
res<-residuals(lr)
plot(res,ylab="residuals", main="Residual Diagnostic")
abline(h=0,col='red')
acf(res)
qqnorm(res)
qqline(res, col='red')
#(c)
plot.ts(berkeley, ylab="yearly temperature",main="Berkeley Temperature Time Series")
acf(berkeley, main="ACF Plot of Berkeley")
#(d)
berkeley_diff<-diff(berkeley)
plot.ts(berkeley_diff, ylab="diff yearly temperature",main="Differenced Berkeley Temperature Time Series")
acf(berkeley_diff, main="ACF Plot of Differenced Berkeley")
#Question 3
engtemp<-scan("tpmon.dat",skip=1)
#(a)
engtemp2<-engtemp[1:300]
plot.ts(engtemp2, main="England Monthly Temperature")
acf(engtemp2, main="ACF of England Monthly Temperature" )
#(b)
tcosine<-cos(pi*(2/12)*(1:length(engtemp)))
tsine<-sin(pi*(2/12)*(1:length(engtemp)))
lr<-lm(engtemp~tcosine+tsine)
summary(lr)
#(c)
res<-residuals(lr)[1:300]
plot(res,ylab="residuals", main="Residual Plot")
plot.ts(res,ylab="residuals", main="Residual Time Series Plot")
acf(res, main="ACF Plot of Residuals")
#Question 4
#(b)
install.packages("astsa")
library(astsa)
plot.ts(oil, main="Time Series of Oil Price")
ma52<-filter(oil, sides=2, c(0.5, rep(1,51), 0.5)/52)
lines(ma52, col='blue')
